# Generated by Django 5.1.1 on 2024-09-18 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_customuser_terms"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="pharmacy_name",
            new_name="pharmacyName",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="registration_certificate",
            new_name="registrationCertificate",
        ),
        migrations.RenameField(
            model_name="customuser",
            old_name="registration_number",
            new_name="registrationNumber",
        ),
    ]
